export const GET_AUTHOR_REQUEST = "GET_AUTHOR_REQUEST";
export const GET_AUTHOR_SUCCESS = "GET_AUTHOR_SUCCESS";
export const GET_AUTHOR_FAIL = "GET_AUTHOR_FAIL";

export const AUTHOR_LOGIN_REQUEST = "AUTHOR_LOGIN_REQUEST";
export const AUTHOR_LOGIN_SUCCESS = "AUTHOR_LOGIN_SUCCESS";
export const AUTHOR_LOGIN_FAIL = "AUTHOR_LOGIN_FAIL";

export const AUTHOR_LOGOUT_REQUEST = "AUTHOR_LOGOUT_REQUEST";
export const AUTHOR_LOGOUT_SUCCESS = "AUTHOR_LOGOUT_SUCCESS";
export const AUTHOR_LOGOUT_FAIL = "AUTHOR_LOGOUT_FAIL";

export const AUTHOR_REGISTER_REQUEST = "AUTHOR_REGISTER_REQUEST";
export const AUTHOR_REGISTER_SUCCESS = "AUTHOR_REGISTER_SUCCESS";
export const AUTHOR_REGISTER_FAIL = "AUTHOR_REGISTER_FAIL";

export const AUTHOR_DELETE_REQUEST = "AUTHOR_DELETE_REQUEST";
export const AUTHOR_DELETE_SUCCESS = "AUTHOR_DELETE_SUCCESS";
export const AUTHOR_DELETE_FAIL = "AUTHOR_DELETE_FAIL";

export const POST_AUTHOR_REQUEST = "POST_AUTHOR_REQUEST";
export const POST_AUTHOR_SUCCESS = "POST_AUTHOR_SUCCESS";
export const POST_AUTHOR_FAIL = "POST_AUTHOR_FAIL";

export const PUT_AUTHOR_REQUEST = "PUT_AUTHOR_REQUEST";
export const PUT_AUTHOR_SUCCESS = "PUT_AUTHOR_SUCCESS";
export const PUT_AUTHOR_FAIL = "PUT_AUTHOR_FAIL";

export const GET_AUTHOR_POSTS_REQUEST = "GET_AUTHOR_POSTS_REQUEST";
export const GET_AUTHOR_POSTS_SUCCESS = "GET_AUTHOR_POSTS_SUCCESS";
export const GET_AUTHOR_POSTS_FAIL = "GET_AUTHOR_POSTS_FAIL";
export const GET_AUTHOR_POSTS_RESET = "GET_AUTHOR_POSTS_RESET";


export const GET_AUTHOR_POST_REQUEST = "GET_AUTHOR_POST_REQUEST";
export const GET_AUTHOR_POST_SUCCESS = "GET_AUTHOR_POST_SUCCESS";
export const GET_AUTHOR_POST_FAIL = "GET_AUTHOR_POST_FAIL";
export const GET_AUTHOR_POST_RESET = "GET_AUTHOR_POST_RESET";

export const POST_AUTHOR_POST_REQUEST = "POST_AUTHOR_POST_REQUEST";
export const POST_AUTHOR_POST_SUCCESS = "POST_AUTHOR_POST_SUCCESS";
export const POST_AUTHOR_POST_FAIL = "POST_AUTHOR_POST_FAIL";
export const POST_AUTHOR_POST_RESET = "POST_AUTHOR_POST_RESET";